apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Values.fullnameOverride }}
